name: genderizeio
description: A Dart API wrapper for Genderize.io
version: 1.0.0

repository: https://github.com/agustinustheo/dart-genderizeio

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies: {http: ^0.13.4}
  
